name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Param
          user: addzt
          template: classic
          base: header, activity, repositories, community
          config_timezone: Europe/Moscow
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, percentage
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 8
          
          
        
